# Generated by Django 6.0.1 on 2026-01-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('alias', models.CharField()),
                ('birthdate', models.DateField()),
                ('species', models.CharField()),
                ('famous_phrase', models.CharField()),
                ('citizenship', models.CharField()),
                ('affiliatons', models.JSONField()),
                ('portrayed_by', models.CharField()),
                ('first_appearence', models.CharField()),
            ],
        ),
    ]
