# Generated by Django 6.0.1 on 2026-01-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
