# Generated by Django 6.0.1 on 2026-01-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_character_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='character',
            name='image2',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
