# Generated by Django 6.0.1 on 2026-01-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_image_character_image1_character_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='birthdate',
            field=models.DateField(default='Unknown'),
        ),
    ]
