# Generated by Django 6.0.1 on 2026-01-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_character_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
